// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dehdwtqmswknlxatjqql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlaGR3dHFtc3drbmx4YXRqcXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxOTE4MTEsImV4cCI6MjA4Nzc2NzgxMX0.rI2ysgsB_f1E1ffaO5NV-kKBQghZl1WKe-X2Y3FZOiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});